name 'ls_sql_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ls_sql_server'
long_description 'Installs/Configures ls_sql_server'
version '0.2.23'
supports 'windows'

depends 'windows'
depends 'ls_windows_cluster'
depends 'ls_windows_ad', '>=0.3.7'
