default['ls_sql_server']['netfx3_source'] = '\\\\SCCM\software$\Sources\sxs'
default['ls_sql_server']['sql_account'] = 'thewall.LOCAL\\SQLSVC'
default['ls_sql_server']['sql_source'] = '\\\\SCCM\\software$\\Sources\\SQL2012SP3'
default['ls_sql_server']['sysadmins'] = 'thewall.LOCAL\\SQL Administrators'
default['ls_sql_server']['agent_account_pwd'] = 'p@ssw0rd!'
default['ls_sql_server']['sql_account_pwd'] = 'p@ssw0rd!'
default['ls_sql_server']['cluster'] = 'standalone'
